### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by lgreb** [matthewsklar/PoetryBot#1]
The themes are a little bit of an issue. For science, it pulls in technical words that make no sense together. Sex is simply a bad idea for a random word generator. We should pick either "sea" or "ocean" as one of the themes.

**Comment by Sitranine** [comment]
I think  capitalization, especially of "I" is an issue. I repeat, if we have some way to ensure subject-verb agreement, almost every line would make sense.

**Comment by lgreb** [comment]
Remove unknown as a theme mostly because I have no idea what it will do with that theme.
