### ISSUE TITLE
Blacklist

### ISSUE THREAD

**Issue by Sitranine** [matthewsklar/PoetryBot#3]

**Comment by Sitranine** [comment]
Updated Ban List: (bold for request)
[“Ca”, “.”, “Le”, “Pshaw”, “Duh”, “Dah”, “Pizzazz”, “Wussy”, “Speechifying”, “Verklempt”, “Niner”,“Huh”, “Siddhartha”, “Uh”, “Biz”, “Riz”, “Ms”, “Whiz”, “Bloviation”, “Churchy”, “Polyannaish”, “Noobz”, “Shema”]

**Comment by lgreb** [comment]
Can we ban other languages? Like no more French, German, Russian, Yiddish, or Spanish?
